
#include "local_header.h"
int c_merge_ovlp_m2o_once_init(c_pscmc_env *pe, c_merge_ovlp_m2o_once_struct *kerstr);
void c_merge_ovlp_m2o_once_get_struct_len(size_t *len);
int c_merge_ovlp_m2o_once_get_xlen();
int c_merge_ovlp_m2o_once_get_num_compute_units(c_merge_ovlp_m2o_once_struct *kerstr);
int c_merge_ovlp_m2o_once_exec(c_merge_ovlp_m2o_once_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecmain(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp0(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp1(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp2(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp3(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp4(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp5(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp6(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp7(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp8(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp9(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp10(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp11(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp12(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp14(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp15(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp16(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp17(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp18(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp19(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp20(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp21(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp22(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp23(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp24(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp25(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp26(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_numvec(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_num_ele(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_xblock(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_yblock(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_zblock(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_once_scmc_set_parameter_ovlp(c_merge_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_all_in_one_init(c_pscmc_env *pe, c_merge_ovlp_m2o_all_in_one_struct *kerstr);
void c_merge_ovlp_m2o_all_in_one_get_struct_len(size_t *len);
int c_merge_ovlp_m2o_all_in_one_get_xlen();
int c_merge_ovlp_m2o_all_in_one_get_num_compute_units(c_merge_ovlp_m2o_all_in_one_struct *kerstr);
int c_merge_ovlp_m2o_all_in_one_exec(c_merge_ovlp_m2o_all_in_one_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_merge_ovlp_m2o_all_in_one_scmc_set_parameter_vecmain(c_merge_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_all_in_one_scmc_set_parameter_vecovlps(c_merge_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_all_in_one_scmc_set_parameter_numvec(c_merge_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_all_in_one_scmc_set_parameter_num_ele(c_merge_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_all_in_one_scmc_set_parameter_xblock(c_merge_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_all_in_one_scmc_set_parameter_yblock(c_merge_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_all_in_one_scmc_set_parameter_zblock(c_merge_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_all_in_one_scmc_set_parameter_ovlp(c_merge_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_init(c_pscmc_env *pe, c_merge_ovlp_m2o_struct *kerstr);
void c_merge_ovlp_m2o_get_struct_len(size_t *len);
int c_merge_ovlp_m2o_get_xlen();
int c_merge_ovlp_m2o_get_num_compute_units(c_merge_ovlp_m2o_struct *kerstr);
int c_merge_ovlp_m2o_exec(c_merge_ovlp_m2o_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_merge_ovlp_m2o_scmc_set_parameter_vecmain(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_scmc_set_parameter_vecovlp(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_scmc_set_parameter_ovlpindex(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_scmc_set_parameter_numvec(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_scmc_set_parameter_num_ele(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_scmc_set_parameter_xblock(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_scmc_set_parameter_yblock(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_scmc_set_parameter_zblock(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_m2o_scmc_set_parameter_ovlp(c_merge_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_init(c_pscmc_env *pe, c_merge_ovlp_o2m_once_struct *kerstr);
void c_merge_ovlp_o2m_once_get_struct_len(size_t *len);
int c_merge_ovlp_o2m_once_get_xlen();
int c_merge_ovlp_o2m_once_get_num_compute_units(c_merge_ovlp_o2m_once_struct *kerstr);
int c_merge_ovlp_o2m_once_exec(c_merge_ovlp_o2m_once_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecmain(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp0(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp1(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp2(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp3(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp4(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp5(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp6(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp7(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp8(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp9(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp10(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp11(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp12(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp14(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp15(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp16(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp17(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp18(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp19(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp20(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp21(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp22(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp23(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp24(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp25(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp26(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_numvec(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_num_ele(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_xblock(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_yblock(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_zblock(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_once_scmc_set_parameter_ovlp(c_merge_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_all_in_one_init(c_pscmc_env *pe, c_merge_ovlp_o2m_all_in_one_struct *kerstr);
void c_merge_ovlp_o2m_all_in_one_get_struct_len(size_t *len);
int c_merge_ovlp_o2m_all_in_one_get_xlen();
int c_merge_ovlp_o2m_all_in_one_get_num_compute_units(c_merge_ovlp_o2m_all_in_one_struct *kerstr);
int c_merge_ovlp_o2m_all_in_one_exec(c_merge_ovlp_o2m_all_in_one_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_merge_ovlp_o2m_all_in_one_scmc_set_parameter_vecmain(c_merge_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_all_in_one_scmc_set_parameter_vecovlps(c_merge_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_all_in_one_scmc_set_parameter_numvec(c_merge_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_all_in_one_scmc_set_parameter_num_ele(c_merge_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_all_in_one_scmc_set_parameter_xblock(c_merge_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_all_in_one_scmc_set_parameter_yblock(c_merge_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_all_in_one_scmc_set_parameter_zblock(c_merge_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_all_in_one_scmc_set_parameter_ovlp(c_merge_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_init(c_pscmc_env *pe, c_merge_ovlp_o2m_struct *kerstr);
void c_merge_ovlp_o2m_get_struct_len(size_t *len);
int c_merge_ovlp_o2m_get_xlen();
int c_merge_ovlp_o2m_get_num_compute_units(c_merge_ovlp_o2m_struct *kerstr);
int c_merge_ovlp_o2m_exec(c_merge_ovlp_o2m_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_merge_ovlp_o2m_scmc_set_parameter_vecmain(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_scmc_set_parameter_vecovlp(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_scmc_set_parameter_ovlpindex(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_scmc_set_parameter_numvec(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_scmc_set_parameter_num_ele(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_scmc_set_parameter_xblock(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_scmc_set_parameter_yblock(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_scmc_set_parameter_zblock(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_merge_ovlp_o2m_scmc_set_parameter_ovlp(c_merge_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_init(c_pscmc_env *pe, c_sync_ovlp_m2o_once_struct *kerstr);
void c_sync_ovlp_m2o_once_get_struct_len(size_t *len);
int c_sync_ovlp_m2o_once_get_xlen();
int c_sync_ovlp_m2o_once_get_num_compute_units(c_sync_ovlp_m2o_once_struct *kerstr);
int c_sync_ovlp_m2o_once_exec(c_sync_ovlp_m2o_once_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecmain(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp0(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp1(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp2(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp3(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp4(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp5(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp6(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp7(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp8(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp9(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp10(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp11(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp12(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp14(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp15(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp16(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp17(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp18(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp19(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp20(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp21(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp22(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp23(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp24(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp25(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp26(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_numvec(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_num_ele(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_xblock(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_yblock(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_zblock(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_once_scmc_set_parameter_ovlp(c_sync_ovlp_m2o_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_all_in_one_init(c_pscmc_env *pe, c_sync_ovlp_m2o_all_in_one_struct *kerstr);
void c_sync_ovlp_m2o_all_in_one_get_struct_len(size_t *len);
int c_sync_ovlp_m2o_all_in_one_get_xlen();
int c_sync_ovlp_m2o_all_in_one_get_num_compute_units(c_sync_ovlp_m2o_all_in_one_struct *kerstr);
int c_sync_ovlp_m2o_all_in_one_exec(c_sync_ovlp_m2o_all_in_one_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_sync_ovlp_m2o_all_in_one_scmc_set_parameter_vecmain(c_sync_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_all_in_one_scmc_set_parameter_vecovlps(c_sync_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_all_in_one_scmc_set_parameter_numvec(c_sync_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_all_in_one_scmc_set_parameter_num_ele(c_sync_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_all_in_one_scmc_set_parameter_xblock(c_sync_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_all_in_one_scmc_set_parameter_yblock(c_sync_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_all_in_one_scmc_set_parameter_zblock(c_sync_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_all_in_one_scmc_set_parameter_ovlp(c_sync_ovlp_m2o_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_init(c_pscmc_env *pe, c_sync_ovlp_m2o_struct *kerstr);
void c_sync_ovlp_m2o_get_struct_len(size_t *len);
int c_sync_ovlp_m2o_get_xlen();
int c_sync_ovlp_m2o_get_num_compute_units(c_sync_ovlp_m2o_struct *kerstr);
int c_sync_ovlp_m2o_exec(c_sync_ovlp_m2o_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_sync_ovlp_m2o_scmc_set_parameter_vecmain(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_scmc_set_parameter_vecovlp(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_scmc_set_parameter_ovlpindex(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_scmc_set_parameter_numvec(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_scmc_set_parameter_num_ele(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_scmc_set_parameter_xblock(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_scmc_set_parameter_yblock(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_scmc_set_parameter_zblock(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_m2o_scmc_set_parameter_ovlp(c_sync_ovlp_m2o_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_init(c_pscmc_env *pe, c_sync_ovlp_o2m_once_struct *kerstr);
void c_sync_ovlp_o2m_once_get_struct_len(size_t *len);
int c_sync_ovlp_o2m_once_get_xlen();
int c_sync_ovlp_o2m_once_get_num_compute_units(c_sync_ovlp_o2m_once_struct *kerstr);
int c_sync_ovlp_o2m_once_exec(c_sync_ovlp_o2m_once_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecmain(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp0(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp1(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp2(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp3(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp4(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp5(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp6(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp7(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp8(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp9(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp10(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp11(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp12(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp14(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp15(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp16(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp17(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp18(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp19(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp20(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp21(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp22(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp23(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp24(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp25(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp26(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_numvec(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_num_ele(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_xblock(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_yblock(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_zblock(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_once_scmc_set_parameter_ovlp(c_sync_ovlp_o2m_once_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_all_in_one_init(c_pscmc_env *pe, c_sync_ovlp_o2m_all_in_one_struct *kerstr);
void c_sync_ovlp_o2m_all_in_one_get_struct_len(size_t *len);
int c_sync_ovlp_o2m_all_in_one_get_xlen();
int c_sync_ovlp_o2m_all_in_one_get_num_compute_units(c_sync_ovlp_o2m_all_in_one_struct *kerstr);
int c_sync_ovlp_o2m_all_in_one_exec(c_sync_ovlp_o2m_all_in_one_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_sync_ovlp_o2m_all_in_one_scmc_set_parameter_vecmain(c_sync_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_all_in_one_scmc_set_parameter_vecovlps(c_sync_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_all_in_one_scmc_set_parameter_numvec(c_sync_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_all_in_one_scmc_set_parameter_num_ele(c_sync_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_all_in_one_scmc_set_parameter_xblock(c_sync_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_all_in_one_scmc_set_parameter_yblock(c_sync_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_all_in_one_scmc_set_parameter_zblock(c_sync_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_all_in_one_scmc_set_parameter_ovlp(c_sync_ovlp_o2m_all_in_one_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_init(c_pscmc_env *pe, c_sync_ovlp_o2m_struct *kerstr);
void c_sync_ovlp_o2m_get_struct_len(size_t *len);
int c_sync_ovlp_o2m_get_xlen();
int c_sync_ovlp_o2m_get_num_compute_units(c_sync_ovlp_o2m_struct *kerstr);
int c_sync_ovlp_o2m_exec(c_sync_ovlp_o2m_struct *kerstr, long scmc_internal_g_xlen, long scmc_internal_g_ylen);
int c_sync_ovlp_o2m_scmc_set_parameter_vecmain(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_scmc_set_parameter_vecovlp(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_scmc_set_parameter_ovlpindex(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_scmc_set_parameter_numvec(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_scmc_set_parameter_num_ele(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_scmc_set_parameter_xblock(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_scmc_set_parameter_yblock(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_scmc_set_parameter_zblock(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
int c_sync_ovlp_o2m_scmc_set_parameter_ovlp(c_sync_ovlp_o2m_struct *kerstr, c_pscmc_mem *pm);
