#include "pubdefs.h"

int  openmp_cu_swap_r_8_init (openmp_pscmc_env *  pe ,openmp_cu_swap_r_8_struct *  kerstr );
void  openmp_cu_swap_r_8_get_struct_len (size_t *  len );
int  openmp_cu_swap_r_8_get_num_compute_units (openmp_cu_swap_r_8_struct *  kerstr );
int  openmp_cu_swap_r_8_get_xlen ();
int  openmp_cu_swap_r_8_exec (openmp_cu_swap_r_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_cu_swap_r_8_scmc_set_parameter_cu_cache (openmp_cu_swap_r_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_8_scmc_set_parameter_cu_xyzw (openmp_cu_swap_r_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_8_scmc_set_parameter_adjoint_vec_pids (openmp_cu_swap_r_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_8_scmc_set_parameter_cu_cache_length (openmp_cu_swap_r_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_8_scmc_set_parameter_the_dir_num (openmp_cu_swap_r_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_8_scmc_set_parameter_XYZLEN (openmp_cu_swap_r_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_8_init (openmp_pscmc_env *  pe ,openmp_cu_swap_l_8_struct *  kerstr );
void  openmp_cu_swap_l_8_get_struct_len (size_t *  len );
int  openmp_cu_swap_l_8_get_num_compute_units (openmp_cu_swap_l_8_struct *  kerstr );
int  openmp_cu_swap_l_8_get_xlen ();
int  openmp_cu_swap_l_8_exec (openmp_cu_swap_l_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_cu_swap_l_8_scmc_set_parameter_cu_cache (openmp_cu_swap_l_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_8_scmc_set_parameter_cu_xyzw (openmp_cu_swap_l_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_8_scmc_set_parameter_adjoint_vec_pids (openmp_cu_swap_l_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_8_scmc_set_parameter_cu_cache_length (openmp_cu_swap_l_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_8_scmc_set_parameter_the_dir_num (openmp_cu_swap_l_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_8_scmc_set_parameter_XYZLEN (openmp_cu_swap_l_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_6_init (openmp_pscmc_env *  pe ,openmp_cu_swap_r_6_struct *  kerstr );
void  openmp_cu_swap_r_6_get_struct_len (size_t *  len );
int  openmp_cu_swap_r_6_get_num_compute_units (openmp_cu_swap_r_6_struct *  kerstr );
int  openmp_cu_swap_r_6_get_xlen ();
int  openmp_cu_swap_r_6_exec (openmp_cu_swap_r_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_cu_swap_r_6_scmc_set_parameter_cu_cache (openmp_cu_swap_r_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_6_scmc_set_parameter_cu_xyzw (openmp_cu_swap_r_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_6_scmc_set_parameter_adjoint_vec_pids (openmp_cu_swap_r_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_6_scmc_set_parameter_cu_cache_length (openmp_cu_swap_r_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_6_scmc_set_parameter_the_dir_num (openmp_cu_swap_r_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_r_6_scmc_set_parameter_XYZLEN (openmp_cu_swap_r_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_6_init (openmp_pscmc_env *  pe ,openmp_cu_swap_l_6_struct *  kerstr );
void  openmp_cu_swap_l_6_get_struct_len (size_t *  len );
int  openmp_cu_swap_l_6_get_num_compute_units (openmp_cu_swap_l_6_struct *  kerstr );
int  openmp_cu_swap_l_6_get_xlen ();
int  openmp_cu_swap_l_6_exec (openmp_cu_swap_l_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_cu_swap_l_6_scmc_set_parameter_cu_cache (openmp_cu_swap_l_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_6_scmc_set_parameter_cu_xyzw (openmp_cu_swap_l_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_6_scmc_set_parameter_adjoint_vec_pids (openmp_cu_swap_l_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_6_scmc_set_parameter_cu_cache_length (openmp_cu_swap_l_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_6_scmc_set_parameter_the_dir_num (openmp_cu_swap_l_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_cu_swap_l_6_scmc_set_parameter_XYZLEN (openmp_cu_swap_l_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_z_vlo_8_struct *  kerstr );
void  openmp_sort_one_grid_z_vlo_8_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_z_vlo_8_get_num_compute_units (openmp_sort_one_grid_z_vlo_8_struct *  kerstr );
int  openmp_sort_one_grid_z_vlo_8_get_xlen ();
int  openmp_sort_one_grid_z_vlo_8_exec (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_inoutput (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_xyzw (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_cu_cache (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_XLEN (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_YLEN (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_ZLEN (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_ovlp (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_numvec (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_8_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr );
void  openmp_gpu_sort_one_grid_z_vlo_8_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_z_vlo_8_get_num_compute_units (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr );
int  openmp_gpu_sort_one_grid_z_vlo_8_get_xlen ();
int  openmp_gpu_sort_one_grid_z_vlo_8_exec (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_8_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_z_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_y_vlo_8_struct *  kerstr );
void  openmp_sort_one_grid_y_vlo_8_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_y_vlo_8_get_num_compute_units (openmp_sort_one_grid_y_vlo_8_struct *  kerstr );
int  openmp_sort_one_grid_y_vlo_8_get_xlen ();
int  openmp_sort_one_grid_y_vlo_8_exec (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_inoutput (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_xyzw (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_cu_cache (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_XLEN (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_YLEN (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_ZLEN (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_ovlp (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_numvec (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_8_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr );
void  openmp_gpu_sort_one_grid_y_vlo_8_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_y_vlo_8_get_num_compute_units (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr );
int  openmp_gpu_sort_one_grid_y_vlo_8_get_xlen ();
int  openmp_gpu_sort_one_grid_y_vlo_8_exec (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_8_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_y_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_x_vlo_8_struct *  kerstr );
void  openmp_sort_one_grid_x_vlo_8_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_x_vlo_8_get_num_compute_units (openmp_sort_one_grid_x_vlo_8_struct *  kerstr );
int  openmp_sort_one_grid_x_vlo_8_get_xlen ();
int  openmp_sort_one_grid_x_vlo_8_exec (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_inoutput (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_xyzw (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_cu_cache (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_XLEN (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_YLEN (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_ZLEN (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_ovlp (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_numvec (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_8_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr );
void  openmp_gpu_sort_one_grid_x_vlo_8_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_x_vlo_8_get_num_compute_units (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr );
int  openmp_gpu_sort_one_grid_x_vlo_8_get_xlen ();
int  openmp_gpu_sort_one_grid_x_vlo_8_exec (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_8_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_x_vlo_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_z_8_struct *  kerstr );
void  openmp_sort_one_grid_z_8_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_z_8_get_num_compute_units (openmp_sort_one_grid_z_8_struct *  kerstr );
int  openmp_sort_one_grid_z_8_get_xlen ();
int  openmp_sort_one_grid_z_8_exec (openmp_sort_one_grid_z_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_inoutput (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_xyzw (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_cu_cache (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_XLEN (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_YLEN (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_ZLEN (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_ovlp (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_numvec (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_8_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_z_8_struct *  kerstr );
void  openmp_gpu_sort_one_grid_z_8_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_z_8_get_num_compute_units (openmp_gpu_sort_one_grid_z_8_struct *  kerstr );
int  openmp_gpu_sort_one_grid_z_8_get_xlen ();
int  openmp_gpu_sort_one_grid_z_8_exec (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_8_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_z_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_y_8_struct *  kerstr );
void  openmp_sort_one_grid_y_8_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_y_8_get_num_compute_units (openmp_sort_one_grid_y_8_struct *  kerstr );
int  openmp_sort_one_grid_y_8_get_xlen ();
int  openmp_sort_one_grid_y_8_exec (openmp_sort_one_grid_y_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_inoutput (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_xyzw (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_cu_cache (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_XLEN (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_YLEN (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_ZLEN (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_ovlp (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_numvec (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_8_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_y_8_struct *  kerstr );
void  openmp_gpu_sort_one_grid_y_8_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_y_8_get_num_compute_units (openmp_gpu_sort_one_grid_y_8_struct *  kerstr );
int  openmp_gpu_sort_one_grid_y_8_get_xlen ();
int  openmp_gpu_sort_one_grid_y_8_exec (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_8_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_y_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_x_8_struct *  kerstr );
void  openmp_sort_one_grid_x_8_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_x_8_get_num_compute_units (openmp_sort_one_grid_x_8_struct *  kerstr );
int  openmp_sort_one_grid_x_8_get_xlen ();
int  openmp_sort_one_grid_x_8_exec (openmp_sort_one_grid_x_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_inoutput (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_xyzw (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_cu_cache (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_XLEN (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_YLEN (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_ZLEN (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_ovlp (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_numvec (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_8_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_x_8_struct *  kerstr );
void  openmp_gpu_sort_one_grid_x_8_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_x_8_get_num_compute_units (openmp_gpu_sort_one_grid_x_8_struct *  kerstr );
int  openmp_gpu_sort_one_grid_x_8_get_xlen ();
int  openmp_gpu_sort_one_grid_x_8_exec (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_8_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_x_8_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_z_vlo_6_struct *  kerstr );
void  openmp_sort_one_grid_z_vlo_6_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_z_vlo_6_get_num_compute_units (openmp_sort_one_grid_z_vlo_6_struct *  kerstr );
int  openmp_sort_one_grid_z_vlo_6_get_xlen ();
int  openmp_sort_one_grid_z_vlo_6_exec (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_inoutput (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_xyzw (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_cu_cache (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_XLEN (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_YLEN (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_ZLEN (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_ovlp (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_numvec (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_vlo_6_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr );
void  openmp_gpu_sort_one_grid_z_vlo_6_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_z_vlo_6_get_num_compute_units (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr );
int  openmp_gpu_sort_one_grid_z_vlo_6_get_xlen ();
int  openmp_gpu_sort_one_grid_z_vlo_6_exec (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_vlo_6_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_z_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_y_vlo_6_struct *  kerstr );
void  openmp_sort_one_grid_y_vlo_6_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_y_vlo_6_get_num_compute_units (openmp_sort_one_grid_y_vlo_6_struct *  kerstr );
int  openmp_sort_one_grid_y_vlo_6_get_xlen ();
int  openmp_sort_one_grid_y_vlo_6_exec (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_inoutput (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_xyzw (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_cu_cache (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_XLEN (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_YLEN (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_ZLEN (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_ovlp (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_numvec (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_vlo_6_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr );
void  openmp_gpu_sort_one_grid_y_vlo_6_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_y_vlo_6_get_num_compute_units (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr );
int  openmp_gpu_sort_one_grid_y_vlo_6_get_xlen ();
int  openmp_gpu_sort_one_grid_y_vlo_6_exec (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_vlo_6_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_y_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_x_vlo_6_struct *  kerstr );
void  openmp_sort_one_grid_x_vlo_6_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_x_vlo_6_get_num_compute_units (openmp_sort_one_grid_x_vlo_6_struct *  kerstr );
int  openmp_sort_one_grid_x_vlo_6_get_xlen ();
int  openmp_sort_one_grid_x_vlo_6_exec (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_inoutput (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_xyzw (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_cu_cache (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_XLEN (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_YLEN (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_ZLEN (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_ovlp (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_numvec (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_vlo_6_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr );
void  openmp_gpu_sort_one_grid_x_vlo_6_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_x_vlo_6_get_num_compute_units (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr );
int  openmp_gpu_sort_one_grid_x_vlo_6_get_xlen ();
int  openmp_gpu_sort_one_grid_x_vlo_6_exec (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_vlo_6_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_x_vlo_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_z_6_struct *  kerstr );
void  openmp_sort_one_grid_z_6_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_z_6_get_num_compute_units (openmp_sort_one_grid_z_6_struct *  kerstr );
int  openmp_sort_one_grid_z_6_get_xlen ();
int  openmp_sort_one_grid_z_6_exec (openmp_sort_one_grid_z_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_inoutput (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_xyzw (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_cu_cache (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_XLEN (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_YLEN (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_ZLEN (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_ovlp (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_numvec (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_z_6_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_z_6_struct *  kerstr );
void  openmp_gpu_sort_one_grid_z_6_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_z_6_get_num_compute_units (openmp_gpu_sort_one_grid_z_6_struct *  kerstr );
int  openmp_gpu_sort_one_grid_z_6_get_xlen ();
int  openmp_gpu_sort_one_grid_z_6_exec (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_z_6_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_z_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_y_6_struct *  kerstr );
void  openmp_sort_one_grid_y_6_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_y_6_get_num_compute_units (openmp_sort_one_grid_y_6_struct *  kerstr );
int  openmp_sort_one_grid_y_6_get_xlen ();
int  openmp_sort_one_grid_y_6_exec (openmp_sort_one_grid_y_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_inoutput (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_xyzw (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_cu_cache (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_XLEN (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_YLEN (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_ZLEN (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_ovlp (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_numvec (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_y_6_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_y_6_struct *  kerstr );
void  openmp_gpu_sort_one_grid_y_6_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_y_6_get_num_compute_units (openmp_gpu_sort_one_grid_y_6_struct *  kerstr );
int  openmp_gpu_sort_one_grid_y_6_get_xlen ();
int  openmp_gpu_sort_one_grid_y_6_exec (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_y_6_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_y_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_init (openmp_pscmc_env *  pe ,openmp_sort_one_grid_x_6_struct *  kerstr );
void  openmp_sort_one_grid_x_6_get_struct_len (size_t *  len );
int  openmp_sort_one_grid_x_6_get_num_compute_units (openmp_sort_one_grid_x_6_struct *  kerstr );
int  openmp_sort_one_grid_x_6_get_xlen ();
int  openmp_sort_one_grid_x_6_exec (openmp_sort_one_grid_x_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_inoutput (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_xyzw (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_cu_cache (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_cu_xyzw (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_adjoint_vec_pids (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_XLEN (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_YLEN (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_ZLEN (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_ovlp (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_numvec (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_grid_cache_len (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sort_one_grid_x_6_scmc_set_parameter_cu_cache_length (openmp_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_init (openmp_pscmc_env *  pe ,openmp_gpu_sort_one_grid_x_6_struct *  kerstr );
void  openmp_gpu_sort_one_grid_x_6_get_struct_len (size_t *  len );
int  openmp_gpu_sort_one_grid_x_6_get_num_compute_units (openmp_gpu_sort_one_grid_x_6_struct *  kerstr );
int  openmp_gpu_sort_one_grid_x_6_get_xlen ();
int  openmp_gpu_sort_one_grid_x_6_exec (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_inoutput (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_xyzw (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_cu_cache (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_cu_xyzw (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_adjoint_vec_pids (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_XLEN (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_YLEN (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_ZLEN (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_ovlp (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_numvec (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_grid_cache_len (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_gpu_sort_one_grid_x_6_scmc_set_parameter_cu_cache_length (openmp_gpu_sort_one_grid_x_6_struct *  kerstr ,openmp_pscmc_mem *  pm );
