#include "pubdefs.h"

int  openmp_merge_ovlp_m2o_once_init (openmp_pscmc_env *  pe ,openmp_merge_ovlp_m2o_once_struct *  kerstr );
void  openmp_merge_ovlp_m2o_once_get_struct_len (size_t *  len );
int  openmp_merge_ovlp_m2o_once_get_num_compute_units (openmp_merge_ovlp_m2o_once_struct *  kerstr );
int  openmp_merge_ovlp_m2o_once_get_xlen ();
int  openmp_merge_ovlp_m2o_once_exec (openmp_merge_ovlp_m2o_once_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecmain (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp0 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp1 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp2 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp3 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp4 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp5 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp6 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp7 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp8 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp9 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp10 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp11 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp12 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp14 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp15 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp16 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp17 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp18 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp19 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp20 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp21 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp22 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp23 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp24 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp25 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_vecovlp26 (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_numvec (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_num_ele (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_xblock (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_yblock (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_zblock (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_once_scmc_set_parameter_ovlp (openmp_merge_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_all_in_one_init (openmp_pscmc_env *  pe ,openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr );
void  openmp_merge_ovlp_m2o_all_in_one_get_struct_len (size_t *  len );
int  openmp_merge_ovlp_m2o_all_in_one_get_num_compute_units (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr );
int  openmp_merge_ovlp_m2o_all_in_one_get_xlen ();
int  openmp_merge_ovlp_m2o_all_in_one_exec (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_merge_ovlp_m2o_all_in_one_scmc_set_parameter_vecmain (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_all_in_one_scmc_set_parameter_vecovlps (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_all_in_one_scmc_set_parameter_numvec (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_all_in_one_scmc_set_parameter_num_ele (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_all_in_one_scmc_set_parameter_xblock (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_all_in_one_scmc_set_parameter_yblock (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_all_in_one_scmc_set_parameter_zblock (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_all_in_one_scmc_set_parameter_ovlp (openmp_merge_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_init (openmp_pscmc_env *  pe ,openmp_merge_ovlp_m2o_struct *  kerstr );
void  openmp_merge_ovlp_m2o_get_struct_len (size_t *  len );
int  openmp_merge_ovlp_m2o_get_num_compute_units (openmp_merge_ovlp_m2o_struct *  kerstr );
int  openmp_merge_ovlp_m2o_get_xlen ();
int  openmp_merge_ovlp_m2o_exec (openmp_merge_ovlp_m2o_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_vecmain (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_vecovlp (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_ovlpindex (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_numvec (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_num_ele (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_xblock (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_yblock (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_zblock (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_m2o_scmc_set_parameter_ovlp (openmp_merge_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_init (openmp_pscmc_env *  pe ,openmp_merge_ovlp_o2m_once_struct *  kerstr );
void  openmp_merge_ovlp_o2m_once_get_struct_len (size_t *  len );
int  openmp_merge_ovlp_o2m_once_get_num_compute_units (openmp_merge_ovlp_o2m_once_struct *  kerstr );
int  openmp_merge_ovlp_o2m_once_get_xlen ();
int  openmp_merge_ovlp_o2m_once_exec (openmp_merge_ovlp_o2m_once_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecmain (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp0 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp1 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp2 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp3 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp4 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp5 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp6 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp7 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp8 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp9 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp10 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp11 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp12 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp14 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp15 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp16 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp17 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp18 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp19 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp20 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp21 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp22 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp23 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp24 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp25 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_vecovlp26 (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_numvec (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_num_ele (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_xblock (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_yblock (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_zblock (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_once_scmc_set_parameter_ovlp (openmp_merge_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_all_in_one_init (openmp_pscmc_env *  pe ,openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr );
void  openmp_merge_ovlp_o2m_all_in_one_get_struct_len (size_t *  len );
int  openmp_merge_ovlp_o2m_all_in_one_get_num_compute_units (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr );
int  openmp_merge_ovlp_o2m_all_in_one_get_xlen ();
int  openmp_merge_ovlp_o2m_all_in_one_exec (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_merge_ovlp_o2m_all_in_one_scmc_set_parameter_vecmain (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_all_in_one_scmc_set_parameter_vecovlps (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_all_in_one_scmc_set_parameter_numvec (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_all_in_one_scmc_set_parameter_num_ele (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_all_in_one_scmc_set_parameter_xblock (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_all_in_one_scmc_set_parameter_yblock (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_all_in_one_scmc_set_parameter_zblock (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_all_in_one_scmc_set_parameter_ovlp (openmp_merge_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_init (openmp_pscmc_env *  pe ,openmp_merge_ovlp_o2m_struct *  kerstr );
void  openmp_merge_ovlp_o2m_get_struct_len (size_t *  len );
int  openmp_merge_ovlp_o2m_get_num_compute_units (openmp_merge_ovlp_o2m_struct *  kerstr );
int  openmp_merge_ovlp_o2m_get_xlen ();
int  openmp_merge_ovlp_o2m_exec (openmp_merge_ovlp_o2m_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_vecmain (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_vecovlp (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_ovlpindex (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_numvec (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_num_ele (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_xblock (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_yblock (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_zblock (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_merge_ovlp_o2m_scmc_set_parameter_ovlp (openmp_merge_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_init (openmp_pscmc_env *  pe ,openmp_sync_ovlp_m2o_once_struct *  kerstr );
void  openmp_sync_ovlp_m2o_once_get_struct_len (size_t *  len );
int  openmp_sync_ovlp_m2o_once_get_num_compute_units (openmp_sync_ovlp_m2o_once_struct *  kerstr );
int  openmp_sync_ovlp_m2o_once_get_xlen ();
int  openmp_sync_ovlp_m2o_once_exec (openmp_sync_ovlp_m2o_once_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecmain (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp0 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp1 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp2 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp3 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp4 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp5 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp6 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp7 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp8 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp9 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp10 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp11 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp12 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp14 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp15 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp16 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp17 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp18 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp19 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp20 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp21 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp22 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp23 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp24 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp25 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_vecovlp26 (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_numvec (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_num_ele (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_xblock (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_yblock (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_zblock (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_once_scmc_set_parameter_ovlp (openmp_sync_ovlp_m2o_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_all_in_one_init (openmp_pscmc_env *  pe ,openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr );
void  openmp_sync_ovlp_m2o_all_in_one_get_struct_len (size_t *  len );
int  openmp_sync_ovlp_m2o_all_in_one_get_num_compute_units (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr );
int  openmp_sync_ovlp_m2o_all_in_one_get_xlen ();
int  openmp_sync_ovlp_m2o_all_in_one_exec (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sync_ovlp_m2o_all_in_one_scmc_set_parameter_vecmain (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_all_in_one_scmc_set_parameter_vecovlps (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_all_in_one_scmc_set_parameter_numvec (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_all_in_one_scmc_set_parameter_num_ele (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_all_in_one_scmc_set_parameter_xblock (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_all_in_one_scmc_set_parameter_yblock (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_all_in_one_scmc_set_parameter_zblock (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_all_in_one_scmc_set_parameter_ovlp (openmp_sync_ovlp_m2o_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_init (openmp_pscmc_env *  pe ,openmp_sync_ovlp_m2o_struct *  kerstr );
void  openmp_sync_ovlp_m2o_get_struct_len (size_t *  len );
int  openmp_sync_ovlp_m2o_get_num_compute_units (openmp_sync_ovlp_m2o_struct *  kerstr );
int  openmp_sync_ovlp_m2o_get_xlen ();
int  openmp_sync_ovlp_m2o_exec (openmp_sync_ovlp_m2o_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_vecmain (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_vecovlp (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_ovlpindex (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_numvec (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_num_ele (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_xblock (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_yblock (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_zblock (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_m2o_scmc_set_parameter_ovlp (openmp_sync_ovlp_m2o_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_init (openmp_pscmc_env *  pe ,openmp_sync_ovlp_o2m_once_struct *  kerstr );
void  openmp_sync_ovlp_o2m_once_get_struct_len (size_t *  len );
int  openmp_sync_ovlp_o2m_once_get_num_compute_units (openmp_sync_ovlp_o2m_once_struct *  kerstr );
int  openmp_sync_ovlp_o2m_once_get_xlen ();
int  openmp_sync_ovlp_o2m_once_exec (openmp_sync_ovlp_o2m_once_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecmain (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp0 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp1 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp2 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp3 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp4 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp5 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp6 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp7 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp8 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp9 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp10 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp11 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp12 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp14 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp15 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp16 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp17 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp18 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp19 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp20 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp21 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp22 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp23 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp24 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp25 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_vecovlp26 (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_numvec (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_num_ele (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_xblock (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_yblock (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_zblock (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_once_scmc_set_parameter_ovlp (openmp_sync_ovlp_o2m_once_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_all_in_one_init (openmp_pscmc_env *  pe ,openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr );
void  openmp_sync_ovlp_o2m_all_in_one_get_struct_len (size_t *  len );
int  openmp_sync_ovlp_o2m_all_in_one_get_num_compute_units (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr );
int  openmp_sync_ovlp_o2m_all_in_one_get_xlen ();
int  openmp_sync_ovlp_o2m_all_in_one_exec (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sync_ovlp_o2m_all_in_one_scmc_set_parameter_vecmain (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_all_in_one_scmc_set_parameter_vecovlps (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_all_in_one_scmc_set_parameter_numvec (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_all_in_one_scmc_set_parameter_num_ele (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_all_in_one_scmc_set_parameter_xblock (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_all_in_one_scmc_set_parameter_yblock (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_all_in_one_scmc_set_parameter_zblock (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_all_in_one_scmc_set_parameter_ovlp (openmp_sync_ovlp_o2m_all_in_one_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_init (openmp_pscmc_env *  pe ,openmp_sync_ovlp_o2m_struct *  kerstr );
void  openmp_sync_ovlp_o2m_get_struct_len (size_t *  len );
int  openmp_sync_ovlp_o2m_get_num_compute_units (openmp_sync_ovlp_o2m_struct *  kerstr );
int  openmp_sync_ovlp_o2m_get_xlen ();
int  openmp_sync_ovlp_o2m_exec (openmp_sync_ovlp_o2m_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_vecmain (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_vecovlp (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_ovlpindex (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_numvec (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_num_ele (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_xblock (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_yblock (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_zblock (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_sync_ovlp_o2m_scmc_set_parameter_ovlp (openmp_sync_ovlp_o2m_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_yee_local_init (openmp_pscmc_env *  pe ,openmp_yee_local_struct *  kerstr );
void  openmp_yee_local_get_struct_len (size_t *  len );
int  openmp_yee_local_get_num_compute_units (openmp_yee_local_struct *  kerstr );
int  openmp_yee_local_get_xlen ();
int  openmp_yee_local_exec (openmp_yee_local_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_yee_local_scmc_set_parameter_inout (openmp_yee_local_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_yee_local_scmc_set_parameter_numvec (openmp_yee_local_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_yee_local_scmc_set_parameter_num_ele (openmp_yee_local_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_yee_local_scmc_set_parameter_xblock (openmp_yee_local_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_yee_local_scmc_set_parameter_yblock (openmp_yee_local_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_yee_local_scmc_set_parameter_zblock (openmp_yee_local_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_yee_local_scmc_set_parameter_ovlp (openmp_yee_local_struct *  kerstr ,openmp_pscmc_mem *  pm );
