#include "pubdefs.h"

int  openmp_Yee_FDTD_W04_2_init (openmp_pscmc_env *  pe ,openmp_Yee_FDTD_W04_2_struct *  kerstr );
void  openmp_Yee_FDTD_W04_2_get_struct_len (size_t *  len );
int  openmp_Yee_FDTD_W04_2_get_num_compute_units (openmp_Yee_FDTD_W04_2_struct *  kerstr );
int  openmp_Yee_FDTD_W04_2_get_xlen ();
int  openmp_Yee_FDTD_W04_2_exec (openmp_Yee_FDTD_W04_2_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_outEB (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_inEB (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_y_cpu_core (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_numvec (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_XLEN (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_YLEN (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_ZLEN (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_ovlp (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_xblock (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_yblock (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_zblock (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_num_ele (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_2_scmc_set_parameter_DT (openmp_Yee_FDTD_W04_2_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_init (openmp_pscmc_env *  pe ,openmp_Yee_FDTD_W04_1_struct *  kerstr );
void  openmp_Yee_FDTD_W04_1_get_struct_len (size_t *  len );
int  openmp_Yee_FDTD_W04_1_get_num_compute_units (openmp_Yee_FDTD_W04_1_struct *  kerstr );
int  openmp_Yee_FDTD_W04_1_get_xlen ();
int  openmp_Yee_FDTD_W04_1_exec (openmp_Yee_FDTD_W04_1_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_outEB (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_inEB (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_y_cpu_core (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_numvec (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_XLEN (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_YLEN (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_ZLEN (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_ovlp (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_xblock (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_yblock (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_zblock (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_num_ele (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_1_scmc_set_parameter_DT (openmp_Yee_FDTD_W04_1_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_init (openmp_pscmc_env *  pe ,openmp_Yee_FDTD_W04_0_struct *  kerstr );
void  openmp_Yee_FDTD_W04_0_get_struct_len (size_t *  len );
int  openmp_Yee_FDTD_W04_0_get_num_compute_units (openmp_Yee_FDTD_W04_0_struct *  kerstr );
int  openmp_Yee_FDTD_W04_0_get_xlen ();
int  openmp_Yee_FDTD_W04_0_exec (openmp_Yee_FDTD_W04_0_struct *  kerstr ,long  scmc_internal_g_xlen ,long  scmc_internal_g_ylen );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_outEB (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_inEB (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_y_cpu_core (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_numvec (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_XLEN (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_YLEN (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_ZLEN (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_ovlp (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_xblock (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_yblock (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_zblock (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_num_ele (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
int  openmp_Yee_FDTD_W04_0_scmc_set_parameter_DT (openmp_Yee_FDTD_W04_0_struct *  kerstr ,openmp_pscmc_mem *  pm );
