(defmacro many-define lst
  (cons 'begin (map (lambda (x) (cons 'define x)) lst))
  )

(many-define
  (NUM_MULTI_STEP_SORT 2)
  (DELTA_X 3.0)
  (DELTA_Y 1.111)
  (DELTA_Z 111.1)
  (DELTA_X 1.0)
  (DELTA_Y 1.0)
  (DELTA_Z 1.0)
  (REAL_DX 1e-3)
  (REAL_MU0 (* 4 m_pi 1e-7))
  (REAL_NE (* 1.e20 DELTA_X DELTA_Y DELTA_Z))
  (REAL_ME 9.1e-31)
  (REAL_E 1.6e-19)
  (REAL_C 299792458.)
  (DT 0.5)
  (DELTAT DT)
  (REAL_DT (* REAL_C DT))
  (E (* REAL_E (sqrt (/ REAL_MU0 REAL_ME REAL_DX))))
  (CONST_E_DENSITY (* REAL_NE REAL_DX REAL_DX REAL_DX))
  (EI_SCALE 1)
  (NPG0 10)
  (NPG1 (/ NPG0 EI_SCALE))
  (NPM0 (/ CONST_E_DENSITY NPG0))
  (NPM1 (/ CONST_E_DENSITY NPG1))

  (XMAX 2)
  (YMAX 2)
  (ZMAX 2)
  (USE_SMALL_NUM_GRIDS 0)
  (NUM_PROCESS 0)
  (NUM_RUNTIME 1)
  (NUM_MAX_RUNTIME 4)
  (NUM_N_HILBERT 3)
  (NUM_N_HILBERT_DIMENSION 3)
  (HILBERT_DIR 0)
  (USE_REDUCE_TO_SMALL 0)
  (REDUCE_TO_SMALL_NUM_GROUPS 0) ;must be dividable by 2**NUM_N_HILBERT_DIMENSION
  (USE_1ST 0)
  (NUM_TIMESTEP 4)
  (NUM_DUMP_TIMESTEP 1)
  (NUM_SPEC 1)
  (USE_KGM 0)
  (USE_DM 0)
  (USE_TORI 1)
  (USE_REL 0)
  (USE_PROFILE 0)
  (USE_VLO 1)
  (USE_MLO_SMALL_PASS 0)

  (TORI_X0 1920)
  (TORI_SOLVE_ERR 1e-13)
  ;cyclone
  (eta_i 4)
  (q_0 2.4)
  (shat 1.6)
  (epsilon_T 0.1)
  (epsilon_B 0.2057)
  (tau 1.0)

  (USE_LHCD_INPUT 0)
  (USE_ECRH_INPUT 0)
  (USE_AVER_OUTPUT 0)
  (ECRH_AMPX 0)
  (ECRH_AMPY 0)
  (ECRH_AMPZ 0)
  (ECRH_KY 0)
  (ECRH_KZ 0)
  (ECRH_LOC_X0 444)
  (ECRH_LOC_Y0 0)
  (ECRH_LOC_Y1 1)
  (ECRH_LOC_Z0 200)
  (ECRH_LOC_Z1 248)
  (ECRH_FREQ 0.85)
  (USE_CALC_WEIGHT 0)
  (USE_NON_UNI_CACHE_DIST 0)
  (GET_NON_UNI_CACHE_DIST (lambda x 1))
  (X_NUMT (arithmetic-shift 1 NUM_N_HILBERT))
  (get_thread_complexity 
    (lambda (x)
      (define x (integer-floor x))
      (define idx (* (+ 0.5 (remainder x X_NUMT)) XMAX))
      (define idz (* (+ 0.5 (quotient x X_NUMT)) ZMAX))
      (* 1000 (+ (GET_INIT_DENSITY_DIST 0 idx 0 idz) 0.02))
      ))
  (CAL_FUN_ONE_PARA 
    (lambda (s x)
      (define s1 (string->symbol s))
      (if (symbol-binded? s1)
	((eval (string->symbol s)) x)
	(begin 
	  (write-string (multi-concat "Warning: symbol " s1 " is unbounded\n" ) current-error-port)
	  (car 0)
	  )))
    )

  (GET_VAR 
    (lambda (s) 
      (define s1 (string->symbol s))
      (if (symbol-binded? s1)
	(eval (string->symbol s))
	(begin 
	  ;(write-string (multi-concat "Warning: symbol " s1 " is unbounded\n" ) current-error-port)
	  0
	  ))))
  (M_0 1)
  (M_1 3672)
  (E_0 -1)
  (E_1 1)
  (USE_CHECKPOINT 0)
  (NUM_CHECKPOINT_TIMESTEP 20000)
  (KROOK_MU_FREQ 0.00)
  (GAPSIO_VERSION 2)
  (USE_FIELD_DUMP_MASK 0)
  (GET_FIELD_DUMP_MASK
    (lambda (x)
      (define x (integer-floor x))
      (define idx (remainder x X_NUMT))
      (if (eq? idx 2) 1 0)
      ))
  (USE_NP_BOUNDARY 0)
  (USE_ABC_DIR 0)
  (USE_PEC_DIR 0)
  (USE_DAMP_DIR 0)
  (ZMID (* 0.5 (arithmetic-shift 1 NUM_N_HILBERT) ZMAX))
  ;(XMID (* 0.5 (arithmetic-shift 1 NUM_N_HILBERT) XMAX))
  (XMID (/ XMAX 2))
  (ALLXMAX XMAX)
  (ALLZMAX (* (arithmetic-shift 1 NUM_N_HILBERT) ZMAX))
  (GET_INIT_FILTER_KROOK
    (lambda (z y x l)
      (cond 
	((< x 5) 1)
	((> x (- ALLXMAX 5)) 1)
	(else 0))))
  (GET_INIT_FILTER_E
    (lambda (z y x l)
      1))
  (GET_INIT_FILTER_B (lambda x 1))
  (USE_FILTER 0)


  (USE_INIT_EB0 0)
  (USE_INIT_V0 1)
  (USE_NON_UNI_TEMPERATURE 1)
  (Kappa_T (* DELTA_X (/ 0.12 2.263)))
  (dsc 
    (lambda (x) 
      (cond
	((> x XMID)
	  (exp (* 0.5 (- XMID x) Kappa_T)))
	((< x (/ XMID 2)) (exp (* (- x (/ XMID 2)) 0.5)))
	(else 1)
	)
      ))
  (GET_INIT_TEMPERATURE_DIST 
    (lambda (i z y x l) 
      (* 
	(case l
	  (0 (/ 1 DELTA_X))
	  (1 (/ 1 DELTA_Y))
	  (2 (/ 1 DELTA_Z))
	  )); (dsc x)
      )
    )

  (USE_NON_UNI_DENSITY 1)
  (USE_INIT_EXT_EB 1)
  (GET_DEV_TYPE  (lambda (x r) 2))
  (GET_DEV_ID  (lambda (x r) 0))
  (GET_NPM (lambda (i) 100))
  (GET_NUM_LOCAL_THREAD_FROM_GLOBAL_TID (lambda x x))
  (GET_MASS 
    (lambda (i) 
      (case i
	(0 (* M_0 NPM0))
	(1 (* M_1 NPM1))
	(else 1)
	)
      ))
  (GET_CHARGE 
    (lambda (i) 
      (case i
	(0 (* E_0 E NPM0))
	(1 (* E_1 E NPM1))
	(else 0)
	)
      ))
  (GET_GRID_CACHE_LEN 
    (lambda (i) 
      (case i
	(0 1280)
	(1 320)
	(else 0)
	) )
    
    )
  (GET_CU_CACHE_LEN 
    (lambda (i) 22240))
  (GET_INIT_LOAD 
    (lambda (i) 
      (case i
	(0 NPG0)
	(1 NPG1)
	(else NPG0)
	)))
  (rmin 60)
  (rmin_d 60)
  (rnui 105)
  (rnui_d 105)
  (GET_INIT_DENSITY_DIST 
    (lambda (i z y x)
      1
      )
    )
  (GET_INIT_VT (lambda (i) (* 1 (case i (0 0.0438) (1 0.0007228) (else 0)))))
  (GET_INIT_E (lambda (z y x l) 0))
  (gen_simulate_B 
    (lambda (x)
      (runc "x/(E*REAL_C/REAL_DX*REAL_ME/REAL_E)")
      ))
  (gen_simulate_E 
    (lambda (x)
      (runc "x/(E*REAL_C*REAL_C/REAL_DX*REAL_ME/REAL_E)")
      ))
  (B0 (gen_simulate_B 2.5))
  (Bvec (vector 0 (* B0 DELTA_X DELTA_Y) 0))
  (GET_INIT_B 
    (lambda (z y x l) 
      ;(write (list x y z l) current-error-port) (newline current-error-port)
      (/ (vector-ref Bvec l) (/ (+ x TORI_X0) TORI_X0))
      )
    )
  (GET_INIT_E0 
    (lambda (z y x l) 
      (/ (rand) 2e19)))
  (CURLD 
    (lambda (vA)
      (lambda (z y x l)
	(case l
	  (0 (- (- (vA z (+ y 1) x 2) (vA z y x 2)) (- (vA (+ z 1) y x 1) (vA z y x 1))))
	  (1 (- (- (vA (+ z 1) y x 0) (vA z y x 0)) (- (vA z y (+ x 1) 2) (vA z y x 2))))
	  (2 (- (- (vA z y (+ x 1) 1) (vA z y x 1)) (- (vA z (+ y 1) x 0) (vA z y x 0))))
	)
      )))
  (CURLDP
    (lambda (vA)
      (lambda (x y z l)
	(case l
	  (0 (- (- (- (vA x (- y 1) z 2) (vA x y z 2)) (- (vA x y (- z 1) 1) (vA x y z 1)))))
	  (1 (- (- (- (vA x y (- z 1) 0) (vA x y z 0)) (- (vA (- x 1) y z 2) (vA x y z 2)))))
	  (2 (- (- (- (vA (- x 1) y z 1) (vA x y z 1)) (- (vA x (- y 1) z 0) (vA x y z 0)))))
	)
      )))
  (GET_INIT_B0 (lambda x (/ (rand) 2e17)))

  (TEMP_0 (* M_0 (pow (GET_INIT_VT 0) 2)))
  (TEMP_1 (* M_1 (pow (GET_INIT_VT 1) 2)))
  (V0X_CONST (/ TEMP_0 (* E_0 E B0 TORI_X0)))
  (V1X_CONST (/ TEMP_1 (* E_1 E B0 TORI_X0)))
  (GET_INIT_V0_x 
    (lambda (i z y x) 
      0
      )
    )
  (GET_INIT_V0_z 
    (lambda (i z y x) 
      0
      )
    )
  (CST_V0 (/ B0 (* 2 TORI_X0 CONST_E_DENSITY E)))
  (GET_INIT_V0_y 
    (lambda (i z y x) 
     0 
      )
    )
  )
